### PR TITLE
Travis-ci: added support for ppc64le

### PR DESCRIPTION
**Pull request by sanjaymsh**
Hi,
I have added support for ppc64le build on travis-ci in the branch . The travis-ci build log can be tracked on the link :https://travis-ci.com/github/sanjaymsh/filtergen/builds/188794961 . I believe it is ready for the final review and merge.
Please have a look on it and if everything looks fine for you then please approve it for merge.

Thanks !!

### CODE REVIEW

**Comment by sanjaymsh** [comment]
Hi , Can someone please have a look on this..

Thanks !!

**Comment by jaqx0r** [comment]
Sorry about this, I forgot all about it.

I don't want to merge this as it is because it's into the debian branch, not the main branch, and also because I am trying to migrate to Github Actions instead of Travis.

**Comment by jaqx0r** [comment]
I'll merge it if you think it's going to help you right now, though, but be warned about the above.

**Comment by sanjaymsh** [comment]
Thanks!!

**Pull request merged**
